name: garnix
version: 0.1.0.0
github: "jkarni/garnix"
license: BSD3
author: "Julian K. Arni"
maintainer: "jkarni@riseup.net"
copyright: "AllRightsReserved"

default-extensions:
  - BangPatterns
  - ConstraintKinds
  - DataKinds
  - DeriveAnyClass
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - DerivingStrategies
  - DerivingVia
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - ImportQualifiedPost
  - InstanceSigs
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - NoImplicitPrelude
  - NumericUnderscores
  - OverloadedLabels
  - OverloadedStrings
  - PackageImports
  - PolyKinds
  - QuantifiedConstraints
  - QuasiQuotes
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeOperators
  - ViewPatterns

dependencies:
  - aeson
  - aeson-pretty
  - aeson-qq
  - amazonka
  - amazonka-s3
  - async
  - attoparsec
  - autodocodec
  - autodocodec-schema
  - auto-update
  - base >= 4.7 && < 5
  - base64-bytestring
  - bytestring
  - casing
  - containers
  - cookie
  - cradle
  - crypton
  - data-default-class
  - directory
  - exceptions
  - extra
  - fast-logger
  - file-embed
  - filepath
  - format-numbers
  - generic-lens
  - generics-eot
  - getopt-generics
  - github
  - github-app
  - github-webhooks
  - hashable
  - hashids
  - hashtables
  - http-client
  - http-client-tls
  - http-conduit
  - http-media
  - http-types
  - interpolate
  - iso-deriving
  - jose
  - jwt
  - lens
  - lens-aeson
  - lens-regex-pcre
  - lifted-async
  - lifted-base
  - monad-control
  - mtl
  - network
  - network-uri
  - nix-derivation
  - oauth2-simple
  - openapi3
  - posix-pty
  - postgresql-typed
  - prettyprinter
  - pretty-show
  - process
  - prometheus
  - random
  - resource-pool
  - resourcet
  - retry
  - row-types
  - row-types-aeson
  - safe-exceptions
  - servant
  - servant-auth
  - servant-auth-server
  - servant-github-webhook
  - servant-rawm
  - servant-rawm-server
  - servant-server
  - shake
  - stm
  - streaming
  - streaming-bytestring
  - string-conversions
  - strip-ansi-escape
  - stripe-concepts
  - stripe-signature
  - systemd
  - tagged
  - template-haskell
  - temporary
  - text
  - time
  - tls
  - transformers-base
  - typed-process
  - unix
  - unordered-containers
  - uuid
  - vector
  - wai
  - wai-app-static
  - wai-extra
  - wai-websockets
  - warp
  - websockets
  - wreq
  - yaml
  - zip-archive

library:
  source-dirs: src

extra-source-files:
  - test/spec/data/create-server-response.json
  - test/spec/data/get-servers-response.json
  - test/spec/data/get-servers-response.json
  - test/spec/data/emptyDir/.gitignore

ghc-options:
  - -Wall
  - -Werror
  - -Wno-name-shadowing
  - -fno-warn-star-is-type
  - -threaded
  - -rtsopts
  - '"-with-rtsopts=-T -N"'
  - -j

executables:
  server:
    source-dirs: exe
    main: Server.hs
    other-modules: []
    dependencies:
      - garnix
  generate-yaml-config-docs:
    source-dirs: exe
    main: GenerateYamlConfigDocs.hs
    other-modules: []
    dependencies:
      - garnix
      - autodocodec-yaml
  convert-hashids:
    source-dirs:
      - exe
    main: convertHashids.hs
    other-modules: []
    dependencies:
      - garnix

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test/spec
      - src
    ghc-options:
      - -O0
      - -fno-warn-incomplete-uni-patterns
    dependencies:
      - binary
      - generic-random
      - hspec
      - hspec-core
      - hspec-discover
      - hspec-golden
      - hspec-golden-aeson
      - HUnit
      - mockery
      - neat-interpolation
      - pcre-light
      - port-utils
      - QuickCheck
      - quickcheck-instances
      - silently
      - turtle
      - unix
